apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
- ../../base

patchesStrategicMerge:
- configmap-patch.yaml
- secret-patch.yaml

commonLabels:
  environment: development

images:
- name: tenants-service
  newName: your-registry/tenants-service
  newTag: development