apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-services

resources:
- ../../base

patchesStrategicMerge:
- configmap-patch.yaml
- secret-patch.yaml

commonLabels:
  environment: development

images:
- name: tenants-service
  newName: 369343193270.dkr.ecr.us-east-1.amazonaws.com/tenants-service
  newTag: latest